### PR TITLE
Fix compatibility with Pillow 10.1.0+

### PR DESCRIPTION
**Pull request by timo-piirmann**
https://pillow.readthedocs.io/en/stable/releasenotes/10.1.0.html#setting-image-mode

### CODE REVIEW

**Comment by timo-piirmann** [comment]
Fixes https://github.com/uploadcare/heif-image-plugin/issues/22

**Review by ran404 — APPROVED** [review]
Looks good!

**Comment by homm** [comment]
It  breaks compatibility with other Pillow versions

**Comment by ran404** [comment]
oh no, in that case need to put a guard like hasattr(self, '_mode') or explicit pillow version check, as it is a break change on the pillow side.

**Comment by timo-piirmann** [comment]
Added the `hasattr` check to see if we're dealing with Pillow > 10.1 or not.

I thought about explicit PIL.__version__ check but it seems that I would need to include additional `packaging` library to make a sensible version check to decide which code to run.

**Comment by ran404** [comment]
Have a look at https://github.com/imageio/imageio/pull/1045/files, perhaps that is a cleaner way to achieve setting the mode?

The pillow docs recommends using `Image.convert(new_mode)` to change the mode for versions > 10.1. 

Pillow version be obtained with:
`from PIL import __version__ as pil_version`, so no additional dependency required.

**Review by homm — APPROVED** [review]

**Comment by homm** [comment]
I don't see a way to run workflows in current PR, so I created #24. All tests passed

**Comment by homm** [comment]
I've released https://pypi.org/project/heif-image-plugin/

**Comment by timo-piirmann** [comment]
Awesome. And thanks for plugin 👍

**Pull request merged**
